<a href="https://colab.research.google.com/github/ankittejyadav/AI/blob/main/Frameworks/TensorFlow_2_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# TensorFlow 2 Exercises for Basic Tensor Manipulation

This notebook provides a set of exercises designed to familiarize you with the basics of tensor manipulation in TensorFlow 2,
which is essential for handling Large Language Models (LLMs).

## Contents
1. Tensor Basics
2. Tensor Operations
3. Manipulating Tensor Shapes
4. Indexing and Slicing
5. Broadcasting
6. Gradients and Differentiation
7. Simple Neural Network Components
8. Data Loading and Preprocessing

Each section will include a brief explanation followed by practical exercises.



## 1. Tensor Basics

**Objective**: Understand how to create tensors, and learn about their types and shapes.

**Exercises**:
1. Create a scalar tensor (0-D tensor) with a specific value.
2. Create a 1-D tensor (vector) with 5 elements.
3. Create a 2-D tensor (matrix) of shape (3, 3).
4. Find the data type (`dtype`) of the tensors created above.
5. Convert a numpy array to a TensorFlow tensor.


In [7]:
import tensorflow as tf
import numpy as np
# 0-D tensor with specific value
scalar_tensor=tf.constant(42)
# 1-D tensor with 5 elements
vector_tensor=tf.constant([1,2,3,4,5])
# 2-D tensor with shape (3,3)
matrix_tensor=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
# find dtype
print("Data type of scalar: ",scalar_tensor.dtype)
print("Data type of vector: ",vector_tensor.dtype)
print("Data type of matrix: ",matrix_tensor.dtype)
# convert numpy arr to tensor
arr=np.array([[1,2,3],[4,5,6]])
tensor_np=tf.convert_to_tensor(arr)
print("converted tensor: ",tensor_np)

Data type of scalar:  <dtype: 'int32'>
Data type of vector:  <dtype: 'int32'>
Data type of matrix:  <dtype: 'int32'>
converted tensor:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)



## 2. Tensor Operations

**Objective**: Perform basic arithmetic operations and learn some advanced operations.

**Exercises**:
1. Add, subtract, multiply, and divide two tensors.
2. Compute the mean and standard deviation of a tensor.
3. Apply a non-linear activation function (like ReLU) to a tensor.
4. Perform matrix multiplication between two 2-D tensors.


In [9]:
import tensorflow as tf
tensor1=tf.constant([[1,2],[3,4]])
tensor2=tf.constant([[5,6],[7,8]])

add=tf.add(tensor1,tensor2)
add

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

In [11]:
subtract=tf.subtract(tensor1,tensor2)
subtract

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]], dtype=int32)>

In [12]:
multiply=tf.multiply(tensor1,tensor2)
multiply

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [13]:
divide=tf.divide(tensor1,tensor2)
divide

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])>

In [14]:
tensor=tf.constant([1,2,3,4,5])
mean=tf.reduce_mean(tensor)
mean

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [19]:
tensor=tf.constant([1.0,2.0,-3.0,4.0,5.0])
std=tf.math.reduce_std(tensor)
std

<tf.Tensor: shape=(), dtype=float32, numpy=2.7856777>

In [20]:
tensor_relu=tf.nn.relu(tensor)
tensor_relu

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 0., 4., 5.], dtype=float32)>

In [21]:
mat_mul=tf.matmul(tensor1,tensor2)
mat_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>


## 3. Manipulating Tensor Shapes

**Objective**: Learn how to reshape and transpose tensors.

**Exercises**:
1. Create a tensor of shape (4, 4), then reshape it to (2, 8).
2. Transpose a 2-D tensor.
3. Flatten a 3-D tensor to a 1-D tensor.


In [22]:
quad_tensor=tf.constant([[1,2,3,4],[5,6,7,8],[9,0,1,2],[3,4,5,6]])
quad_tensor

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2],
       [3, 4, 5, 6]], dtype=int32)>

In [24]:
reshape_tensor=tf.reshape(quad_tensor,(2,8))
reshape_tensor

<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6, 7, 8],
       [9, 0, 1, 2, 3, 4, 5, 6]], dtype=int32)>

In [25]:
transpose_tensor=tf.transpose(quad_tensor)
transpose_tensor

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 5, 9, 3],
       [2, 6, 0, 4],
       [3, 7, 1, 5],
       [4, 8, 2, 6]], dtype=int32)>

In [26]:
tensor_3d=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
tensor_3d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]], dtype=int32)>

In [27]:
flatten_tensor=tf.reshape(tensor_3d,[-1])
flatten_tensor

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3], dtype=int32)>


## 4. Indexing and Slicing

**Objective**: Access specific elements or slices of a tensor.

**Exercises**:
1. Extract a specific element from a tensor.
2. Slice a portion of a tensor.
3. Use boolean tensor indexing to filter elements.


In [29]:
specific_element=quad_tensor[2,3]
specific_element

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [30]:
slice_tensor=quad_tensor[0:2,1:3]
slice_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [6, 7]], dtype=int32)>

In [32]:
boolean_mask=tf.constant([[True,False,False,True],[False,True,True,False],[False,True,True,False],[True,False,False,True]])
filtered_tensor=tf.boolean_mask(quad_tensor,boolean_mask)
filtered_tensor

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 4, 6, 7, 0, 1, 3, 6], dtype=int32)>


## 5. Broadcasting

**Objective**: Understand and apply broadcasting rules in tensor operations.

**Exercises**:
1. Perform an element-wise addition between tensors of different shapes.
2. Broadcast a smaller tensor to match the shape of a larger tensor in an operation.



## 6. Gradients and Differentiation

**Objective**: Basic introduction to automatic differentiation.

**Exercises**:
1. Use `tf.GradientTape` to compute derivatives.
2. Find the gradient of a simple function with respect to one of its inputs.



## 7. Data Loading and Preprocessing

**Objective**: Use `tf.data` for efficient data handling.

**Exercises**:
1. Create a simple dataset using `tf.data.Dataset`.
2. Apply a transformation (like mapping) to the dataset.
3. Batch and shuffle the dataset.
